default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  min_messages: notice
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_DATABASE'] %>
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>

integration:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

preprod:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
